import 'package:flutter/material.dart';
import 'package:savesome/utils/database.dart';

import 'dashboard.dart';

class MyDetails extends StatefulWidget {
  final double monthlyUsageLimit;
  final String currencySymbol;

  MyDetails({this.monthlyUsageLimit = 0.0, this.currencySymbol = '₹'});

  @override
  _MyDetailsState createState() => _MyDetailsState();
}

class _MyDetailsState extends State<MyDetails> {
  TextEditingController _myController;
  double monthlyExpenseLimit;
  double weeklyExpenseLimit;
  double dailyExpenseLimit;
  int dayInMonth;
  String dropdownValue;
  String currencySymbol;
  bool buttonStatus = false;
  void updateResults() {
    try {
      monthlyExpenseLimit = double.parse(_myController.text.toString());
      weeklyExpenseLimit =
          ((monthlyExpenseLimit / 4) * 10).roundToDouble() / 10;
      dailyExpenseLimit =
          ((monthlyExpenseLimit / dayInMonth) * 10).roundToDouble() / 10;
      if (monthlyExpenseLimit > 0.0) {
        buttonStatus = true;
      } else {
        buttonStatus = false;
      }
      setState(() {});
    } catch (e) {
      print(e);
    }
  }

  Map<String, String> countryToCurrency = {
    'Afghanistan': 'Af',
    'Akrotiri and Dhekelia': '€',
    'Albania': 'L',
    'Alderney': '£',
    'Algeria': 'د.ج',
    'American Samoa': '\$',
    'Andorra': '€',
    'Angola': 'Kz',
    'Anguilla': '\$',
    'Antigua and Barbuda': '\$',
    'Argentina': '\$',
    'Armenia': 'Դ',
    'Aruba': 'ƒ',
    'Ascension Island': '£',
    'Australia': '\$',
    'Austria': '€',
    'Azerbaijan': 'ман',
    'Bahamas': '\$',
    'Bahrain': 'ب.د',
    'Bangladesh': '৳',
    'Barbados': '\$',
    'Belarus': 'Br',
    'Belgium': '€',
    'Belize': '\$',
    'Benin': '₣',
    'Bermuda': '\$',
    'Bhutan': '',
    'Bhutan': '₹',
    'Bolivia': 'Bs.',
    'Bosnia and Herzegovina': 'КМ',
    'Botswana': 'P',
    'Brazil': 'R\$',
    'British Indian Ocean Territory': '£',
    'British Indian Ocean Territory': '\$',
    'British Virgin Islands': '\$',
    'Brunei': '\$',
    'Brunei': '\$',
    'Bulgaria': 'лв',
    'Burkina Faso': '₣',
    'Burundi': '₣',
    'Cambodia': '៛',
    'Cameroon': '₣',
    'Canada': '\$',
    'Cape Verde': '\$',
    'Cayman Islands': '\$',
    'Central African Republic': '₣',
    'Chad': '₣',
    'Chile': '\$',
    'China': '¥',
    'Coconut Islands': '\$',
    'Colombia': '\$',
    'Congo (Brazzaville)': '₣',
    'Congo (Kinshasa)': '₣',
    'Cook Islands': '\$',
    'Costa Rica': '₡',
    'Côte d\'Ivoire': '₣',
    'Croatia': 'Kn',
    'Cuba': '\$',
    'Cyprus': '€',
    'Czech Republic': 'Kč',
    'Denmark': 'kr',
    'Djibouti': '₣',
    'Dominica': '\$',
    'Dominican Republic': '\$',
    'Egypt': '£',
    'Equatorial Guinea': '₣',
    'Eritrea': 'Nfk',
    'Estonia': '€',
    'Ethiopia': '',
    'Falkland Islands': '£',
    'Fiji': '\$',
    'Finland': '€',
    'France': '€',
    'French Polynesia': '₣',
    'Gabon': '₣',
    'Gambia': 'D',
    'Georgia': 'ლ',
    'Germany': '€',
    'Ghana': '₵',
    'Gibraltar': '£',
    'Great Britain': '£',
    'Greece': '€',
    'Grenada': '\$',
    'Guam': '\$',
    'Guatemala': 'Q',
    'Guinea': '₣',
    'Guinea-Bissau': '₣',
    'Guyana': '\$',
    'Haiti': 'G',
    'Haiti': '\$',
    'Honduras': 'L',
    'Hong Kong': '\$',
    'Hungary': 'Ft',
    'Iceland': 'Kr',
    'India': '₹',
    'Indonesia': 'Rp',
    'Iran': '﷼',
    'Iraq': 'ع.د',
    'Ireland': '€',
    'Isle of Maine': '£',
    'Israel': '₪',
    'Italy': '€',
    'Jamaica': '\$',
    'Japan': '¥',
    'Jordan': 'د.ا',
    'Kazakhstan': '〒',
    'Kenya': 'Sh',
    'Kiribati': '\$',
    'Kosovo': '€',
    'Kosovo': 'din',
    'Kuwait': 'د.ك',
    'Kyrgyzstan': '',
    'Laos': '₭',
    'Latvia': '€',
    'Lebanon': 'ل.ل',
    'Lesotho': 'L',
    'Lesotho': 'R',
    'Liberia': '\$',
    'Libya': 'ل.د',
    'Lichtenstein': '₣',
    'Lithuania': '€',
    'Luxembourg': '€',
    'Macao': 'P',
    'Macedonia': 'ден',
    'Madagascar': '',
    'Malawi': 'MK',
    'Malaysia': 'RM',
    'Maldives': 'ރ.',
    'Mali': '₣',
    'Malta': '€',
    'Marshall Islands': '\$',
    'Mauritania': 'UM',
    'Mauritius': '₨',
    'Mexico': '\$',
    'Micronesia': '\$',
    'Moldova': 'L',
    'Monaco': '€',
    'Mongolia': '₮',
    'Montenegro': '€',
    'Montserrat': '\$',
    'Morocco': 'د.م.',
    'Mozambique': 'MTn',
    'Myanmar (Burma)': 'K',
    'Namibia': '\$',
    'Namibia': 'R',
    'Nauru': '\$',
    'Nepal': '₨',
    'Netherlands': '€',
    'New Caledonia': '₣',
    'New Zealand': '\$',
    'Nicaragua': 'C\$',
    'Niger': '₣',
    'Nigeria': '₦',
    'Niue': '\$',
    'North Cyprus': '₤',
    'North Korea': '₩',
    'Northern Mariana Islands': '\$',
    'Norway': 'kr',
    'Oman': 'ر.ع.',
    'Pacific Remote islands': '\$',
    'Pakistan': '₨',
    'Palau': '\$',
    'Palestine': '₪',
    'Panama': 'B/.',
    'Panama': '\$',
    'Papua New Guinea': 'K',
    'Paraguay': '₲',
    'Peru': 'S/.',
    'Philippines': '₱',
    'Pitcairn Island': '\$',
    'Poland': 'zł',
    'Portugal': '€',
    'Puerto Rico': '\$',
    'Qatar': 'ر.ق',
    'Romania': 'L',
    'Russia': 'р.',
    'Rwanda': '₣',
    'Saint Helena': '£',
    'Saint Kitts and Nevis': '\$',
    'Saint Lucia': '\$',
    'Saint Vincent and Grenadine': '\$',
    'Samoa': 'T',
    'San-Marino': '€',
    'Sao Tome and Principe': 'Db',
    'Saudi Arabia': 'ر.س',
    'Senegal': '₣',
    'Serbia': 'din',
    'Seychelles': '₨',
    'Sierra Leone': 'Le',
    'Singapore': '\$',
    'Singapore': '\$',
    'Slovakia': '€',
    'Slovenia': '€',
    'Solomon Islands': '\$',
    'Somalia': 'Sh',
    'South Africa': 'R',
    'South Korea': '₩',
    'South Ossetia': 'ლ',
    'South Ossetia': 'р.',
    'Spain': '€',
    'Sri Lanka': 'Rs',
    'Sudan': '£',
    'Suriname': '\$',
    'Swaziland': 'L',
    'Sweden': 'kr',
    'Switzerland': '₣',
    'Syria': 'ل.س',
    'Taiwan': '\$',
    'Tajikistan': 'ЅМ',
    'Tanzania': 'Sh',
    'Thailand': '฿',
    'Togo': '₣',
    'Tonga': 'T\$',
    'Trinidad and Tobago': '\$',
    'Tristan da Cunha': '£',
    'Tunisia': 'د.ت',
    'Turkey': '₤',
    'Turkmenistan': 'm',
    'Turks and Caicos Islands': '\$',
    'Tuvalu': '\$',
    'UAE': 'د.إ',
    'Uganda': 'Sh',
    'Ukraine': '₴',
    'United States of America': '\$',
    'Uruguay': '\$',
    'US Virgin Islands': '\$',
    'Uzbekistan': '',
    'Vanuatu': 'Vt',
    'Vatican': '€',
    'Venezuela': 'Bs F',
    'Vietnam': '₫',
    'Wallis and Futuna': '₣',
    'Yemen': '﷼',
    'Zambia': 'ZK',
    'Zimbabwe': '\$',
  };
  Map<String, String> currencyToCountry = {
    'Af': 'Afghanistan',
    '€': 'Akrotiri and Dhekelia',
    'L': 'Albania',
    '£': 'Alderney',
    'د.ج': 'Algeria',
    '\$': 'American Samoa',
    '€': 'Andorra',
    'Kz': 'Angola',
    '\$': 'Anguilla',
    '\$': 'Antigua and Barbuda',
    '\$': 'Argentina',
    'Դ': 'Armenia',
    'ƒ': 'Aruba',
    '£': 'Ascension Island',
    '\$': 'Australia',
    '€': 'Austria',
    'ман': 'Azerbaijan',
    '\$': 'Bahamas',
    'ب.د': 'Bahrain',
    '৳': 'Bangladesh',
    '\$': 'Barbados',
    'Br': 'Belarus',
    '€': 'Belgium',
    '\$': 'Belize',
    '₣': 'Benin',
    '\$': 'Bermuda',
    '': 'Bhutan',
    '₹': 'Bhutan',
    'Bs.': 'Bolivia',
    'КМ': 'Bosnia and Herzegovina',
    'P': 'Botswana',
    'R\$': 'Brazil',
    '£': 'British Indian Ocean Territory',
    '\$': 'British Indian Ocean Territory',
    '\$': 'British Virgin Islands',
    '\$': 'Brunei',
    '\$': 'Brunei',
    'лв': 'Bulgaria',
    '₣': 'Burkina Faso',
    '₣': 'Burundi',
    '៛': 'Cambodia',
    '₣': 'Cameroon',
    '\$': 'Canada',
    '\$': 'Cape Verde',
    '\$': 'Cayman Islands',
    '₣': 'Central African Republic',
    '₣': 'Chad',
    '\$': 'Chile',
    '¥': 'China',
    '\$': 'Coconut Islands',
    '\$': 'Colombia',
    '₣': 'Congo (Brazzaville)',
    '₣': 'Congo (Kinshasa)',
    '\$': 'Cook Islands',
    '₡': 'Costa Rica',
    '₣': 'Côte d\'Ivoire',
    'Kn': 'Croatia',
    '\$': 'Cuba',
    '€': 'Cyprus',
    'Kč': 'Czech Republic',
    'kr': 'Denmark',
    '₣': 'Djibouti',
    '\$': 'Dominica',
    '\$': 'Dominican Republic',
    '£': 'Egypt',
    '₣': 'Equatorial Guinea',
    'Nfk': 'Eritrea',
    '€': 'Estonia',
    '': 'Ethiopia',
    '£': 'Falkland Islands',
    '\$': 'Fiji',
    '€': 'Finland',
    '€': 'France',
    '₣': 'French Polynesia',
    '₣': 'Gabon',
    'D': 'Gambia',
    'ლ': 'Georgia',
    '€': 'Germany',
    '₵': 'Ghana',
    '£': 'Gibraltar',
    '£': 'Great Britain',
    '€': 'Greece',
    '\$': 'Grenada',
    '\$': 'Guam',
    'Q': 'Guatemala',
    '₣': 'Guinea',
    '₣': 'Guinea-Bissau',
    '\$': 'Guyana',
    'G': 'Haiti',
    '\$': 'Haiti',
    'L': 'Honduras',
    '\$': 'Hong Kong',
    'Ft': 'Hungary',
    'Kr': 'Iceland',
    '₹': 'India',
    'Rp': 'Indonesia',
    '﷼': 'Iran',
    'ع.د': 'Iraq',
    '€': 'Ireland',
    '£': 'Isle of Maine',
    '₪': 'Israel',
    '€': 'Italy',
    '\$': 'Jamaica',
    '¥': 'Japan',
    'د.ا': 'Jordan',
    '〒': 'Kazakhstan',
    'Sh': 'Kenya',
    '\$': 'Kiribati',
    '€': 'Kosovo',
    'din': 'Kosovo',
    'د.ك': 'Kuwait',
    '': 'Kyrgyzstan',
    '₭': 'Laos',
    '€': 'Latvia',
    'ل.ل': 'Lebanon',
    'L': 'Lesotho',
    'R': 'Lesotho',
    '\$': 'Liberia',
    'ل.د': 'Libya',
    '₣': 'Lichtenstein',
    '€': 'Lithuania',
    '€': 'Luxembourg',
    'P': 'Macao',
    'ден': 'Macedonia',
    '': 'Madagascar',
    'MK': 'Malawi',
    'RM': 'Malaysia',
    'ރ.': 'Maldives',
    '₣': 'Mali',
    '€': 'Malta',
    '\$': 'Marshall Islands',
    'UM': 'Mauritania',
    '₨': 'Mauritius',
    '\$': 'Mexico',
    '\$': 'Micronesia',
    'L': 'Moldova',
    '€': 'Monaco',
    '₮': 'Mongolia',
    '€': 'Montenegro',
    '\$': 'Montserrat',
    'د.م.': 'Morocco',
    'MTn': 'Mozambique',
    'K': 'Myanmar (Burma)',
    '\$': 'Namibia',
    'R': 'Namibia',
    '\$': 'Nauru',
    '₨': 'Nepal',
    '€': 'Netherlands',
    '₣': 'New Caledonia',
    '\$': 'New Zealand',
    'C\$': 'Nicaragua',
    '₣': 'Niger',
    '₦': 'Nigeria',
    '\$': 'Niue',
    '₤': 'North Cyprus',
    '₩': 'North Korea',
    '\$': 'Northern Mariana Islands',
    'kr': 'Norway',
    'ر.ع.': 'Oman',
    '\$': 'Pacific Remote islands',
    '₨': 'Pakistan',
    '\$': 'Palau',
    '₪': 'Palestine',
    'B/.': 'Panama',
    '\$': 'Panama',
    'K': 'Papua New Guinea',
    '₲': 'Paraguay',
    'S/.': 'Peru',
    '₱': 'Philippines',
    '\$': 'Pitcairn Island',
    'zł': 'Poland',
    '€': 'Portugal',
    '\$': 'Puerto Rico',
    'ر.ق': 'Qatar',
    'L': 'Romania',
    'р.': 'Russia',
    '₣': 'Rwanda',
    '£': 'Saint Helena',
    '\$': 'Saint Kitts and Nevis',
    '\$': 'Saint Lucia',
    '\$': 'Saint Vincent and Grenadine',
    'T': 'Samoa',
    '€': 'San-Marino',
    'Db': 'Sao Tome and Principe',
    'ر.س': 'Saudi Arabia',
    '₣': 'Senegal',
    'din': 'Serbia',
    '₨': 'Seychelles',
    'Le': 'Sierra Leone',
    '\$': 'Singapore',
    '\$': 'Singapore',
    '€': 'Slovakia',
    '€': 'Slovenia',
    '\$': 'Solomon Islands',
    'Sh': 'Somalia',
    'R': 'South Africa',
    '₩': 'South Korea',
    'ლ': 'South Ossetia',
    'р.': 'South Ossetia',
    '€': 'Spain',
    'Rs': 'Sri Lanka',
    '£': 'Sudan',
    '\$': 'Suriname',
    'L': 'Swaziland',
    'kr': 'Sweden',
    '₣': 'Switzerland',
    'ل.س': 'Syria',
    '\$': 'Taiwan',
    'ЅМ': 'Tajikistan',
    'Sh': 'Tanzania',
    '฿': 'Thailand',
    '₣': 'Togo',
    'T\$': 'Tonga',
    '\$': 'Trinidad and Tobago',
    '£': 'Tristan da Cunha',
    'د.ت': 'Tunisia',
    '₤': 'Turkey',
    'm': 'Turkmenistan',
    '\$': 'Turks and Caicos Islands',
    '\$': 'Tuvalu',
    'د.إ': 'UAE',
    'Sh': 'Uganda',
    '₴': 'Ukraine',
    '\$': 'United States of America',
    '\$': 'Uruguay',
    '\$': 'US Virgin Islands',
    '': 'Uzbekistan',
    'Vt': 'Vanuatu',
    '€': 'Vatican',
    'Bs F': 'Venezuela',
    '₫': 'Vietnam',
    '₣': 'Wallis and Futuna',
    '﷼': 'Yemen',
    'ZK': 'Zambia',
    '\$': 'Zimbabwe',
  };

  @override
  void initState() {
    currencySymbol = widget.currencySymbol;
    DateTime today = DateTime.now();
    dayInMonth = DateTime(today.year, today.month + 1, 0).day;
    _myController = TextEditingController();
    _myController.addListener(updateResults);
    monthlyExpenseLimit = widget.monthlyUsageLimit;
    weeklyExpenseLimit = ((monthlyExpenseLimit / 4) * 10).roundToDouble() / 10;
    dailyExpenseLimit =
        ((monthlyExpenseLimit / dayInMonth) * 10).roundToDouble() / 10;
    super.initState();
  }

  @override
  void dispose() {
    _myController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: MediaQuery.of(context).size.width,
              child: Text(
                'Enter Monthly Expense Limit',
                textScaleFactor: 1.0,
                textAlign: TextAlign.center,
                style: TextStyle(
                    color: Colors.purple,
                    fontSize: 26,
                    fontWeight: FontWeight.w500),
              ),
            ),
            Container(
              width: MediaQuery.of(context).size.width / 2,
              child: TextField(
                textAlign: TextAlign.center,
                style: TextStyle(
                    fontSize: 24,
                    color: Color(0xFFae00ff),
                    fontWeight: FontWeight.w500),
                controller: _myController,
                keyboardType: TextInputType.number,
                decoration:
                    InputDecoration(hintText: monthlyExpenseLimit.toString()),
              ),
            ),
            SizedBox(
              height: 30.0,
            ),
            Container(
              width: MediaQuery.of(context).size.width,
              child: Text(
                'Monthly Limit(approx): $monthlyExpenseLimit',
                textScaleFactor: 1.0,
                textAlign: TextAlign.center,
                style: TextStyle(
                    color: Colors.grey,
                    fontSize: 22,
                    fontWeight: FontWeight.w500),
              ),
            ),
            Container(
              width: MediaQuery.of(context).size.width,
              child: Text(
                'Weekly Limit(approx): $weeklyExpenseLimit',
                textScaleFactor: 1.0,
                textAlign: TextAlign.center,
                style: TextStyle(
                    color: Colors.grey,
                    fontSize: 22,
                    fontWeight: FontWeight.w500),
              ),
            ),
            Container(
              width: MediaQuery.of(context).size.width,
              child: Text(
                'Daily Limit(approx): $dailyExpenseLimit',
                textScaleFactor: 1.0,
                textAlign: TextAlign.center,
                style: TextStyle(
                    color: Colors.grey,
                    fontSize: 22,
                    fontWeight: FontWeight.w500),
              ),
            ),
            SizedBox(
              height: 30.0,
            ),
            Divider(),
            Container(
              width: MediaQuery.of(context).size.width,
              child: Text(
                'Currency Symbol',
                textScaleFactor: 1.0,
                textAlign: TextAlign.center,
                style: TextStyle(
                    color: Colors.purple,
                    fontSize: 26,
                    fontWeight: FontWeight.w500),
              ),
            ),
            DropdownButton(
              value: currencyToCountry[currencySymbol],
              items: <String>[
                'Afghanistan',
                'Akrotiri and Dhekelia',
                'Albania',
                'Alderney',
                'Algeria',
                'American Samoa',
                'Andorra',
                'Angola',
                'Anguilla',
                'Antigua and Barbuda',
                'Argentina',
                'Armenia',
                'Aruba',
                'Ascension Island',
                'Australia',
                'Austria',
                'Azerbaijan',
                'Bahamas',
                'Bahrain',
                'Bangladesh',
                'Barbados',
                'Belarus',
                'Belgium',
                'Belize',
                'Benin',
                'Bermuda',
                'Bhutan',
                'Bhutan',
                'Bolivia',
                'Bosnia and Herzegovina',
                'Botswana',
                'Brazil',
                'British Indian Ocean Territory',
                'British Indian Ocean Territory',
                'British Virgin Islands',
                'Brunei',
                'Brunei',
                'Bulgaria',
                'Burkina Faso',
                'Burundi',
                'Cambodia',
                'Cameroon',
                'Canada',
                'Cape Verde',
                'Cayman Islands',
                'Central African Republic',
                'Chad',
                'Chile',
                'China',
                'Coconut Islands',
                'Colombia',
                'Congo (Brazzaville)',
                'Congo (Kinshasa)',
                'Cook Islands',
                'Costa Rica',
                'Côte d\'Ivoire',
                'Croatia',
                'Cuba',
                'Cyprus',
                'Czech Republic',
                'Denmark',
                'Djibouti',
                'Dominica',
                'Dominican Republic',
                'Egypt',
                'Equatorial Guinea',
                'Eritrea',
                'Estonia',
                'Ethiopia',
                'Falkland Islands',
                'Fiji',
                'Finland',
                'France',
                'French Polynesia',
                'Gabon',
                'Gambia',
                'Georgia',
                'Germany',
                'Ghana',
                'Gibraltar',
                'Great Britain',
                'Greece',
                'Grenada',
                'Guam',
                'Guatemala',
                'Guinea',
                'Guinea-Bissau',
                'Guyana',
                'Haiti',
                'Haiti',
                'Honduras',
                'Hong Kong',
                'Hungary',
                'Iceland',
                'India',
                'Indonesia',
                'Iran',
                'Iraq',
                'Ireland',
                'Isle of Maine',
                'Israel',
                'Italy',
                'Jamaica',
                'Japan',
                'Jordan',
                'Kazakhstan',
                'Kenya',
                'Kiribati',
                'Kosovo',
                'Kosovo',
                'Kuwait',
                'Kyrgyzstan',
                'Laos',
                'Latvia',
                'Lebanon',
                'Lesotho',
                'Lesotho',
                'Liberia',
                'Libya',
                'Lichtenstein',
                'Lithuania',
                'Luxembourg',
                'Macao',
                'Macedonia',
                'Madagascar',
                'Malawi',
                'Malaysia',
                'Maldives',
                'Mali',
                'Malta',
                'Marshall Islands',
                'Mauritania',
                'Mauritius',
                'Mexico',
                'Micronesia',
                'Moldova',
                'Monaco',
                'Mongolia',
                'Montenegro',
                'Montserrat',
                'Morocco',
                'Mozambique',
                'Myanmar (Burma)',
                'Namibia',
                'Namibia',
                'Nauru',
                'Nepal',
                'Netherlands',
                'New Caledonia',
                'New Zealand',
                'Nicaragua',
                'Niger',
                'Nigeria',
                'Niue',
                'North Cyprus',
                'North Korea',
                'Northern Mariana Islands',
                'Norway',
                'Oman',
                'Pacific Remote islands',
                'Pakistan',
                'Palau',
                'Palestine',
                'Panama',
                'Panama',
                'Papua New Guinea',
                'Paraguay',
                'Peru',
                'Philippines',
                'Pitcairn Island',
                'Poland',
                'Portugal',
                'Puerto Rico',
                'Qatar',
                'Romania',
                'Russia',
                'Rwanda',
                'Saint Helena',
                'Saint Kitts and Nevis',
                'Saint Lucia',
                'Saint Vincent and Grenadine',
                'Samoa',
                'San-Marino',
                'Sao Tome and Principe',
                'Saudi Arabia',
                'Senegal',
                'Serbia',
                'Seychelles',
                'Sierra Leone',
                'Singapore',
                'Singapore',
                'Slovakia',
                'Slovenia',
                'Solomon Islands',
                'Somalia',
                'South Africa',
                'South Korea',
                'South Ossetia',
                'South Ossetia',
                'Spain',
                'Sri Lanka',
                'Sudan',
                'Suriname',
                'Swaziland',
                'Sweden',
                'Switzerland',
                'Syria',
                'Taiwan',
                'Tajikistan',
                'Tanzania',
                'Thailand',
                'Togo',
                'Tonga',
                'Trinidad and Tobago',
                'Tristan da Cunha',
                'Tunisia',
                'Turkey',
                'Turkmenistan',
                'Turks and Caicos Islands',
                'Tuvalu',
                'UAE',
                'Uganda',
                'Ukraine',
                'United States of America',
                'Uruguay',
                'US Virgin Islands',
                'Uzbekistan',
                'Vanuatu',
                'Vatican',
                'Venezuela',
                'Vietnam',
                'Wallis and Futuna',
                'Yemen',
                'Zambia',
                'Zimbabwe',
              ].map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                );
              }).toList(),
              onChanged: (String newValue) {
                setState(() {
                  dropdownValue = newValue;
                  currencySymbol = countryToCurrency[dropdownValue];
                });
              },
            ),
            Container(
              width: MediaQuery.of(context).size.width,
              child: Text(
                'Currency Symbol: $currencySymbol',
                textScaleFactor: 1.0,
                textAlign: TextAlign.center,
                style: TextStyle(
                    color: Colors.grey,
                    fontSize: 22,
                    fontWeight: FontWeight.w500),
              ),
            ),
            SizedBox(
              height: 30.0,
            ),
            Divider(),
            RaisedButton(
                color: Colors.purple,
                padding: EdgeInsets.all(10.0),
                child: Text(
                  'update',
                  style: TextStyle(
                      color: Colors.white,
                      fontSize: 26,
                      fontWeight: FontWeight.w500),
                ),
                onPressed: buttonStatus
                    ? () async {
                        DataBase.setCurrencySign(currencySymbol);
                        DataBase.setMonthlyUsageLimit(monthlyExpenseLimit);
                        Navigator.pop(context);
                      }
                    : null),
          ],
        ),
      ),
    );
  }
}
